### ISSUE TITLE
Remove reset of "types" field

### ISSUE THREAD

**Issue by ScrapsPrograms** [vuejs/tsconfig#18]
I'm guessing originally the reset of "types" was put in place when the `tsconfig.dom.json` still used the `tsconfig.node.json` import. Now, however, this reset has become redundant; the field is not set within the base `tsconfig.json`.

Due to this reset, I ran into an issue where none of my @types imports were loaded in. The empty array does not let TypeScript revert to the default configuration.

It should be safe to remove the line `"types": []`, so people may use their installed @types again.

**Comment by haoqunjiang** [comment]
As commented in the source, it is "set to empty to avoid accidental inclusion of unwanted types".

Relying on the automatic inclusion of the `@types/*` module is not a good idea (most of the time they just pollute the global namespace), and it's also bad for performance.
Furthermore, it doesn't affect your application type:
> This option does not affect how @types/* are included in your application code

https://www.typescriptlang.org/tsconfig/#types

**Comment by haoqunjiang** [comment]
One more data point: the TS team has wanted to set `"types": []` by default in `tsc --init` since long ago: https://github.com/microsoft/TypeScript/issues/39354
