### ISSUE TITLE
Enhancement: a separate config entry for `module: node16/nodenext`

### ISSUE THREAD

**Issue by haoqunjiang** [vuejs/tsconfig#2]
References:
- https://www.typescriptlang.org/tsconfig#node16nodenext-nightly-builds
- https://www.typescriptlang.org/tsconfig#moduleResolution
- https://www.typescriptlang.org/docs/handbook/esm-node.html
- https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#esm-nodejs

Note that don't use `node12` because as said in https://github.com/microsoft/TypeScript/issues/46452
> Node 14.8 added top-level `await`, but Node 12 doesn't have it. I think this omission is enough of a wart that starting at Node 12 is the wrong move.

**Comment by segevfiner** [comment]
You are now using `bundler` which is the right approach here. `node16/nodenext` proved to be problematic with bundlers.

**Comment by sodatea** [comment]
Yeah, I'm thinking that maybe `node16/nodenext` does not fit into this package… After all, one always needs a bundler to build `.vue` files.
