### ISSUE TITLE
when i use this package, the tsconfig.json has occur 2 errors like this image,as follow, how to solve it,is this packages called tsconfig's issue? 

### ISSUE THREAD

**Issue by Henrycheheng** [vuejs/tsconfig#22]
![image](https://github.com/vuejs/tsconfig/assets/48849602/a418f78d-d9b1-4505-bdad-4b4163a1bf36)

**Comment by Henrycheheng** [comment]
![image](https://github.com/vuejs/tsconfig/assets/48849602/156b23d9-d3d3-42b1-9672-56ae2f5828b3)

**Comment by Henrycheheng** [comment]
and this is Unknown compiler option 'verbatimModuleSyntax,  ts's version, i'm use ^4.7.0

**Comment by xiaoxiangmoe** [comment]
@Henrycheheng Try using ^5.1.6

**Comment by Henrycheheng** [comment]
OK thank you. I'll try this.

**Comment by dawidpstrak** [comment]
I'm having same issue, updating typescript with 5.1.6 not resolving this issue for me.
