### ISSUE TITLE
Import of vue-i18n fails on vue/tsconfig versions 0.4.0

### ISSUE THREAD

**Issue by jaggarnaut** [vuejs/tsconfig#23]
When i try to install vue-i18n@9 it says:

Could not find a declaration file for module 'vue-i18n'. '/home/user/repo/node_modules/vue-i18n/dist/vue-i18n.esm-bundler.js' implicitly has an 'any' type.
  There are types at '/home/user/repo/node_modules/vue-i18n/dist/vue-i18n.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-i18n' library may need to update its package.json or typings.ts(7016)

Works fine with 0.2.0. Fails with every version greater than that.

**Comment by sodatea** [comment]
I believe this has been fixed in `vue-i18n` 9.3.
If you still encounter this issue after updating `vue-i18n`, please open a new issue with a reproduction link. Thanks!.
