### ISSUE TITLE
Enhancement: a dedicated config for libraries

### ISSUE THREAD

**Issue by haoqunjiang** [vuejs/tsconfig#5]
Should have `skipLibCheck: false` in that config.

But let's wait till https://github.com/microsoft/TypeScript/issues/29118 lands in TypeScript so that the configuration won't be too complex.

**Comment by dpschen** [comment]
It has been implemented in https://github.com/microsoft/TypeScript/pull/50403 and been released with TypeScript 5 😄

**Comment by sodatea** [comment]
`tsconfig.lib.json` added in v0.5.0.
As for the `skipLibCheck: false` configuration, now that https://github.com/vuejs/core/pull/9261 has been merged, we'll add it when 3.4 stable is out and this package drops support for 3.3.

**Comment by haoqunjiang** [comment]
🤔 I'm still thinking about this issue.
https://majors.nullvoxpopuli.com/q?minors=on&old=&packages=vue
There are still about 2/5 Vue 3.x users are on version <= 3.3 as of today.
Should I discontinue support for Vue 3.3 now or wait till the percentage drops to something like 1/5? I'm a bit torn.

**Comment by haoqunjiang** [comment]
It's officially less than 1/5 of all Vue 3 downloads now.
I think we should do it.

<img width="1028" alt="image" src="https://github.com/user-attachments/assets/11f83c55-d788-4700-92f8-6c621ec40a6f">
