### ISSUE TITLE
tsconfig throws errors with TypeScript 5.0

### ISSUE THREAD

**Issue by mxschmitt** [vuejs/tsconfig#6]
Currently these two options are set: `importsNotUsedAsValues` and `preserveValueImports`:

https://github.com/vuejs/tsconfig/blob/5b933516638a949d7f035728dc643fcd2f567699/tsconfig.json#L19-L23

which result with [TypeScript 5.0-beta ](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/)in an error.
```
error TS5101: Flag 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify 'ignoreDeprecations: "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.

error TS5101: Flag 'preserveValueImports' is deprecated and will stop functioning in TypeScript 5.5. Specify 'ignoreDeprecations: "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.
```

### Workaround:

```json
{
  "compilerOptions": {
    "ignoreDeprecations": "5.0"
  }
}
```

in your config.

**Comment by mat813** [comment]
TypeScript 5.0 is out now.

**Comment by doberkofler** [comment]
I'm using `@tsconfig/node18-strictest` and get the following error:

```bash
error TS5101: Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.
```

```json
{
  "extends": "@tsconfig/node18-strictest",
  "compilerOptions": {
    "module": "esnext"
  },
  "ts-node": {
    "esm": true
  }
}
```

**Comment by recallwei** [comment]
+1

**Comment by zokizuan** [comment]
+1

**Comment by green-anger** [comment]
If you use TS 5.0 in package.json, e.g.

```json
"devDependencies": {
  ...
  "typescript": "^5.0.3"
}
```
then in your tsconfig.json you can now use [Verbatim Module Syntax](https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax) which replaces the two options, in their respective TSConfig Reference sections it says:

> Deprecated in favor of [verbatimModuleSyntax](https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax).

When you add it, you'll get another error:

> Option 'isolatedModules' is redundant and cannot be specified with option 'verbatimModuleSyntax'.

So, in the end the following config worked for me:

```json
"compilerOptions": {
  ...
  // "isolatedModules": true,
  // "preserveValueImports": true,
  // "importsNotUsedAsValues": "error",
  "verbatimModuleSyntax": true,
}
```

**Comment by verata-veritatis** [comment]
My tsconfig.app.json uses `@vue/tsconfig/tsconfig.web.json`, so using `verbatimModuleSyntax` doesn't help in this case...

**Comment by joerick** [comment]
If you're using `@vue/tsconfig/tsconfig.web.json` or similar, you can reset those properties that are erroring when you enable `verbatimModuleSyntax`

This worked for me:

```js
{
  "extends": "@vue/tsconfig/tsconfig.web.json",
  "compilerOptions": {
    // workaround for https://github.com/vuejs/tsconfig/issues/6
    "preserveValueImports": false,
    "importsNotUsedAsValues": "remove",
    "verbatimModuleSyntax": true,
     // end workaround
  },
}
```

**Comment by yisuslopez45** [comment]
> Si estás usando `@vue/tsconfig/tsconfig.web.json` o similar, puede restablecer las propiedades que están cometiendo errores cuando habilita `verbatimModuleSyntax`
> 
> Esto funcionó para mí:
> 
> ```js
> {
>   "extends": "@vue/tsconfig/tsconfig.web.json",
>   "compilerOptions": {
>     // workaround for https://github.com/vuejs/tsconfig/issues/6
>     "preserveValueImports": false,
>     "importsNotUsedAsValues": "remove",
>     "verbatimModuleSyntax": true,
>     // end workaround
>   },
> }
> ```

solved my problem
